# Generated by Django 5.2 on 2025-11-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='creator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
